_BASE_: "./Base-DensePose-RCNN-FPN.yaml"
MODEL:
  KEYPOINT_ON: True 
  DENSEPOSE_ON: True
  WEIGHTS: "./pretrained_weights/X101-MIDv2-kpt.pth"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NAME: "DensePoseKTNv2Heads"
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseKTNHead"
    PREDICTOR: "DensePoseKTNv2PredictorV3"
    KPT_ON: True
    KPT_CLASSIFIER_WEIGHT_DIR: "pretrained_weights/KTN_models/keypoints_kpt_classifier_weights.pkl"
    KPT_SURF_RELATION_DIR: "pretrained_weights/KTN_models/kpt_surface_relationships.pkl"
    POOLER_RESOLUTION: 28
    HEATMAP_SIZE: 112
    UP_SCALE: 2
    KPT_UP_SCALE: 2
    INDEX_WEIGHTS: 2.0
    FG_IOU_THRESHOLD: 0.65
    FG_MASK_THRESHOLD: 0.3
    DECODER_MULTI_SCALE_ON: True
  ROI_KEYPOINT_HEAD:
    LOSS_WEIGHT: 0.1
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  # MAX_ITER: 260000
  # STEPS: (200000, 240000)
  # IMS_PER_BATCH: 8
  # BASE_LR: 0.005
  CHECKPOINT_PERIOD: 10000

DATASETS:
  TRAIN: ("densepose_coco_2014_train", "densepose_coco_2014_valminusminival")

VERSION: 2
