_BASE_: "./Base-DensePose-RCNN-FPN.yaml"
MODEL:
  KEYPOINT_ON: True 
  DENSEPOSE_ON: True
  WEIGHTS: "./pretrained_weights/hrnet-w32-MIDv2-kpt.pth"
  BACKBONE:
    NAME: "build_hrfpn_backbone"
  RPN:
    IN_FEATURES: ['p1', 'p2', 'p3', 'p4', 'p5']
  ROI_HEADS:
    IN_FEATURES: ['p1', 'p2', 'p3', 'p4', 'p5']
    NAME: "DensePoseKTNv2Heads"
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseKTNHead"
    PREDICTOR: "DensePoseKTNv2PredictorV3"
    KPT_ON: True
    KPT_SURF_RELATION_DIR: "projects/KTNv2/comm_knowledge/kpt_surf_crkg.pkl"
    PART_SURF_RELATION_DIR: "projects/KTNv2/comm_knowledge/part_surf_crkg.pkl"
    BBOX_SURF_RELATION_DIR: "projects/KTNv2/comm_knowledge/person_surf_crkg.pkl"
    POOLER_RESOLUTION: 28
    HEATMAP_SIZE: 112
    UP_SCALE: 2
    KPT_UP_SCALE: 2
    INDEX_WEIGHTS: 2.0
    FG_IOU_THRESHOLD: 0.65
    FG_MASK_THRESHOLD: 0.3
    DECODER_MULTI_SCALE_ON: True
  ROI_KEYPOINT_HEAD:
    LOSS_WEIGHT: 0.1
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
  IMS_PER_BATCH: 16
  BASE_LR: 0.03
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "norm"
  CHECKPOINT_PERIOD: 10000

DATASETS:
  TRAIN: ("densepose_coco_2014_train", "densepose_coco_2014_valminusminival")

VERSION: 2
